# Generated by Django 2.1.7 on 2021-06-09 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companymaster', '0003_auto_20210602_1527'),
        ('companytransaction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companykeyshareholder',
            name='pdf',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='companymaster.PDFPage'),
        ),
        migrations.AddField(
            model_name='companyofferingstatus',
            name='date_of_listing_pdf',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='date_of_listing_pdf', to='companymaster.PDFPage'),
        ),
        migrations.AddField(
            model_name='companyofferingstatus',
            name='offering_announcement_date_pdf',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='offering_announcement_date_pdf', to='companymaster.PDFPage'),
        ),
        migrations.AddField(
            model_name='companyofferingstatus',
            name='offering_end_date_pdf',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='offering_end_date_pdf', to='companymaster.PDFPage'),
        ),
        migrations.AddField(
            model_name='companyofferingstatus',
            name='offering_price_announcement_date_pdf',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='offering_price_announcement_date_pdf', to='companymaster.PDFPage'),
        ),
        migrations.AddField(
            model_name='companyofferingstatus',
            name='offering_start_date_pdf',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='offering_start_date_pdf', to='companymaster.PDFPage'),
        ),
        migrations.AddField(
            model_name='companyofferingstatus',
            name='postpone_date_pdf',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='postpone_date_pdf', to='companymaster.PDFPage'),
        ),
        migrations.AddField(
            model_name='companyofferingstatus',
            name='share_issue_date_pdf',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='share_issue_date_pdf', to='companymaster.PDFPage'),
        ),
        migrations.AddField(
            model_name='companyofferingstatus',
            name='use_of_proceeds_pdf',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='use_of_proceeds_pdf', to='companymaster.PDFPage'),
        ),
        migrations.AddField(
            model_name='companyofferingstatus',
            name='withdrawn_date_pdf',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='withdrawn_date_pdf', to='companymaster.PDFPage'),
        ),
        migrations.AddField(
            model_name='companyrepresentative',
            name='pdf',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='companymaster.PDFPage'),
        ),
        migrations.AddField(
            model_name='fundpartyauditor',
            name='pdf',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='companymaster.PDFPage'),
        ),
        migrations.AddField(
            model_name='fundpartyleadunderwiter',
            name='pdf',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='companymaster.PDFPage'),
        ),
        migrations.AddField(
            model_name='fundpartyunderwriter',
            name='pdf',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='companymaster.PDFPage'),
        ),
    ]
