# Generated by Django 2.1.7 on 2021-06-10 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companymaster', '0003_auto_20210602_1527'),
        ('companytransaction', '0002_auto_20210609_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyfinancial',
            name='cash_pdf',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cash_pdf', to='companymaster.PDFPage'),
        ),
        migrations.AddField(
            model_name='companyfinancial',
            name='debt_pdf',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='debt_pdf', to='companymaster.PDFPage'),
        ),
        migrations.AddField(
            model_name='companyfinancial',
            name='equity_pdf',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='equity_pdf', to='companymaster.PDFPage'),
        ),
        migrations.AddField(
            model_name='companyfinancial',
            name='last_12_month_sales_pdf',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='last_12_month_sales', to='companymaster.PDFPage'),
        ),
        migrations.AddField(
            model_name='companyfinancial',
            name='revenue_pdf',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='revenue_pdf', to='companymaster.PDFPage'),
        ),
        migrations.AddField(
            model_name='companyfinancial',
            name='total_assets_pdf',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='total_assets_pdf', to='companymaster.PDFPage'),
        ),
        migrations.AddField(
            model_name='companyofferingshares',
            name='lockup_period_pdf',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lockup_period_pdf', to='companymaster.PDFPage'),
        ),
        migrations.AddField(
            model_name='companyofferingshares',
            name='offer_amount_min_pdf',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='offer_amount_min_pdf', to='companymaster.PDFPage'),
        ),
        migrations.AddField(
            model_name='companyofferingshares',
            name='price_range_min_pdf',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='price_range_min_pdf', to='companymaster.PDFPage'),
        ),
        migrations.AddField(
            model_name='companyofferingshares',
            name='quiet_period_expiration_pdf',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quiet_period_expiration_pdf', to='companymaster.PDFPage'),
        ),
        migrations.AddField(
            model_name='companyofferingshares',
            name='registration_fee_pdf',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='registration_fee_pdf', to='companymaster.PDFPage'),
        ),
        migrations.AddField(
            model_name='companyofferingshares',
            name='shares_offered_min_pdf',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='shares_offered_min_pdf', to='companymaster.PDFPage'),
        ),
        migrations.AddField(
            model_name='companyofferingshares',
            name='total_offering_exp_pdf',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='total_offering_exp_pdf', to='companymaster.PDFPage'),
        ),
    ]
